name: Build SFML Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize and update submodules
      run: |
        git submodule update --init --recursive

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Extract Version from README
      id: extract-version
      run: |
        $version = (Select-String -Path README -Pattern 'Version \d+\.\d+\.\d+' | Select-Object -First 1).Matches.Value -replace 'Version ', ''
        Write-Output "::set-output name=version::$version"

    - name: Create Artifact
      run: |
        New-Item -ItemType Directory -Path release
        Copy-Item -Path build\Release\SFML_GAME.exe -Destination release\SFML_GAME.exe
      shell: powershell

    - name: Check directory contents
      run: |
        Get-ChildItem -Path build/Release
      shell: pwsh

    - name: Publish Artifact
      id: publish_artifact
      uses: actions/upload-artifact@v4
      with:
        name: SFML_GAME-${{ steps.extract-version.outputs.version }}
        path: release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.extract-version.outputs.version }}
        release_name: Release ${{ steps.extract-version.outputs.version }}

    - name: Get Artifact Path
      id: get_artifact_path
      run: echo "::set-output name=artifact_path::$(find release -name 'SFML_GAME-*.zip')"

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.get_artifact_path.outputs.artifact_path }}
        asset_name: SFML_GAME-${{ steps.extract-version.outputs.version }}.zip
        asset_content_type: application/zip
        