name: Build SFML Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize and update submodules
      run: |
        git submodule update --init --recursive

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Extract Version from README
      id: extract-version
      run: |
        $version = (Select-String -Path README -Pattern 'Version \d+\.\d+\.\d+' | Select-Object -First 1).Matches.Value -replace 'Version ', ''
        Write-Output "::set-output name=version::$version"

    - name: Check directory contents
      run: |
        Get-ChildItem -Path build/Release
      shell: pwsh

    - name: Echo extracted version
      run: |
        echo "Extracted version: ${{ steps.extract-version.outputs.version }}"
      shell: pwsh

    - name: Compress SFML_GAME.exe into ZIP
      run: |
        Compress-Archive -Path "build/Release/SFML_GAME.exe" -DestinationPath "SFML_GAME-${{ steps.extract-version.outputs.version }}.zip"
      shell: powershell


    - name: Create lightweight tag
      run: git tag v${{ steps.extract-version.outputs.version }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.extract-version.outputs.version }}
        release_name: Release ${{ steps.extract-version.outputs.version }}
    - name: Delete lightweight tag
      run: git tag -d v${{ steps.extract-version.outputs.version }}
