name: Build SFML Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        git checkout 84e807598d245c658ffe3cc02c61ad0ec13a1d2f
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install

    - name: Install dependencies
      run: .\vcpkg\vcpkg install --feature-flags=manifests

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake

    - name: Build
      run: cmake --build build --config Release