name: Build SFML Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize and update submodules
      run: |
        git submodule update --init --recursive

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Extract Version from README
      id: extract-version
      run: |
        version=$(grep -o 'Version [0-9]\+\.[0-9]\+\.[0-9]\+' README | awk '{print $2}')
        echo "::set-output name=version::$version"

    - name: Create TAR Archive
      run: |
        cd build/Release
        tar -cvf SFML_GAME-${{ steps.extract-version.outputs.version }}.tar SFML_GAME.exe
        mv SFML_GAME-${{ steps.extract-version.outputs.version }}.tar ../../../sfml-game-${{ steps.extract-version.outputs.version }}.tar
      shell: cmd

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: sfml-game
        path: SFML_GAME-${{ steps.extract-version.outputs.version }}.tar
